2022-02-18 14:24:33,702 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f469be21070>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/4233b025843627b9b3ca2bd875d35508
2022-02-18 14:24:33,703 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f469a0e3130>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/4233b025843627b9b3ca2bd875d35508
2022-02-18 14:24:33,704 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f469a0e32b0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/4233b025843627b9b3ca2bd875d35508
